##
##  Makefile -- Build procedure for sample granska Apache module
##  Autogenerated via ``apxs -n granska -g''.
##

builddir=.
top_srcdir=/etc/httpd
top_builddir=/usr/lib64/httpd
include /usr/lib64/httpd/build/special.mk

#   the used tools
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_granska.o mod_granska.lo mod_granska.slo mod_granska.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/granska

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

#### below is only for development
mocklibrary: 
	g++ -fPIC -c mockgranska.cpp -o mockgranska.o 
	g++ -shared -o libmockgranska.so mockgranska.o
